version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    networks:
      - monitoring-net
      - lookup
    ports:
      - 9090:9090
    volumes:
      - $PWD/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    networks:
      - monitoring-net
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
      - grafana_provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    container_name: loki
    networks:
      - monitoring-net
    ports:
      - 3100:3100
    volumes:
      - $PWD/configs/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    container_name: promtail
    networks:
      - monitoring-net
    volumes:
      - $PWD/configs/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail-config.yaml -print-config-stderr


volumes:
  grafana_data:
    name: grafana_data
  grafana_log:
    name: grafana_log
  grafana_provisioning:
    name: grafana_provisioning

networks:
  monitoring-net:
    name: monitoring-net
  lookup:
    name: lookup
    external: true
