version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    networks:
      - stg0
    volumes:
      - $PWD/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    networks:
      stg0:
        ipv4_address: 172.30.0.71
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_log:/var/log/grafana
      - grafana_provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    container_name: loki
    networks:
      - stg0
    volumes:
      - $PWD/configs/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    container_name: promtail
    networks:
      - stg0
    volumes:
      - $PWD/configs/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/promtail-config.yaml -print-config-stderr


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - stg0

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - stg0
    privileged: true
    devices:
      - /dev/kmsg


volumes:
  grafana_data:
    name: grafana_data
  grafana_log:
    name: grafana_log
  grafana_provisioning:
    name: grafana_provisioning

networks:
  stg0:
    name: stg0
    external: true
